# Generated by Django 2.2.11 on 2020-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='employee',
        ),
        migrations.AddField(
            model_name='procedure',
            name='employee',
            field=models.ManyToManyField(to='offer.Employee'),
        ),
    ]
