# Generated by Django 2.2.11 on 2020-03-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200311_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('OMiR', 'Oddział Modernizacji i Remontów'), ('WZP', 'Wydział Zamówień Publicznych'), ('PGK', 'Pion Głównego Księgowego'), ('DYREKTOR', 'Dyrektor')], default='OMiR', max_length=1),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='open',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('member', 'Członek Komisji'), ('secretary', 'Sekretarz'), ('chairman', 'Przewodniczący'), ('director', 'Dyrektor')], default='member', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Employee')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Procedure')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='employees',
            field=models.ManyToManyField(through='offer.Role', to='offer.Employee'),
        ),
    ]
