# Generated by Django 2.2.11 on 2020-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200312_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('OMiR', 'Oddział Modernizacji i Remontów'), ('WZP', 'Wydział Zamówień Publicznych'), ('PGK', 'Pion Głównego Księgowego'), ('DYREKTOR', 'Dyrektor')], default='OMiR', max_length=8),
        ),
    ]
