# Generated by Django 2.2.11 on 2020-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20200312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='numer',
            field=models.CharField(max_length=20),
        ),
    ]
