# Generated by Django 2.2.11 on 2020-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20200312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
