# Generated by Django 2.2.11 on 2020-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20200314_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='company_address',
            field=models.CharField(default='adres firmy', max_length=170),
        ),
        migrations.AddField(
            model_name='offert',
            name='company_mail',
            field=models.EmailField(default='mail@wp.pl', max_length=254),
        ),
        migrations.AddField(
            model_name='offert',
            name='company_name',
            field=models.CharField(default='firma', max_length=70),
        ),
        migrations.AlterField(
            model_name='offert',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
