# Generated by Django 2.2.11 on 2020-03-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20200314_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='surname',
            new_name='last_name',
        ),
    ]
