# Generated by Django 2.2.11 on 2020-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20200317_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('Członek Komisji', 'Członek Komisji'), ('Sekretarz', 'Sekretarz'), ('Przewodniczący', 'Przewodniczący'), ('Dyrektor', 'Dyrektor')], default='member', max_length=20),
        ),
    ]
