# Generated by Django 2.2.11 on 2020-03-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_remove_procedure_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offert',
            name='votes',
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('comment_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rates', models.IntegerField(default=0)),
                ('offert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offert')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
