# Generated by Django 2.2.11 on 2020-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_auto_20200320_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
