# Generated by Django 2.2.11 on 2020-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_auto_20200321_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='rates',
            field=models.CharField(choices=[('TAK', 'OK'), ('NIE', 'NIE OK')], default=None, max_length=20),
        ),
    ]
